/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Livraria;
import java.sql.ResultSet;
import utilitarios.Persistence;

/**
 *
 * @author Masds
 */
public class JintPesquisar extends javax.swing.JInternalFrame {

    /**
     * Creates new form JintPesquisar
     */
    public JintPesquisar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_pesquisar = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        lb_infoprinc = new javax.swing.JLabel();
        rad_editora = new javax.swing.JRadioButton();
        rad_livro = new javax.swing.JRadioButton();
        lb_categoria = new javax.swing.JLabel();
        lb_tipopesquisa = new javax.swing.JLabel();
        cb_categorias = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("PESQUISAR LIVRO");

        txt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisarActionPerformed(evt);
            }
        });

        bt_pesquisar.setText("PESQUISAR");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        lb_infoprinc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_infoprinc.setText("INSIRA O NOME DO LIVRO OU EDITORA E ESPECIFIQUE A CATEGORIA");

        rad_editora.setText("EDITORA");

        rad_livro.setText("TÍTULO");

        lb_categoria.setText("Categoria:");

        lb_tipopesquisa.setText("Selecione o que deseja pesquisar:");

        cb_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "HQ", "ROMANCE", "DRAMA." }));
        cb_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb_tipopesquisa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rad_livro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rad_editora)
                            .addGap(69, 69, 69)
                            .addComponent(lb_categoria)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lb_infoprinc)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_infoprinc)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tipopesquisa)
                    .addComponent(rad_editora)
                    .addComponent(rad_livro)
                    .addComponent(cb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_categoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_pesquisar)
                    .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_categoriasActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        String campo = "";
        String categoria ="";
        if(rad_livro.isSelected()){
            campo = "titulo";
        }
        if(rad_editora.isSelected()){
            campo = "editora";
        }
        Persistence conexao = new Persistence();
        conexao.criaConexao();
        ResultSet retornoQuery = conexao.executaSQL("select * from livros where " + campo + " = '" +txt_pesquisar.getText()+"' and categoria='"+cb_categorias.getSelectedItem()+"'");
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void txt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesquisarActionPerformed

    private static JintPesquisar form=null;
    public static JintPesquisar getInstance(){
        if(form == null){
            form = new JintPesquisar();
        }
        return form;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JComboBox<String> cb_categorias;
    private javax.swing.JLabel lb_categoria;
    private javax.swing.JLabel lb_infoprinc;
    private javax.swing.JLabel lb_tipopesquisa;
    private javax.swing.JRadioButton rad_editora;
    private javax.swing.JRadioButton rad_livro;
    private javax.swing.JTextField txt_pesquisar;
    // End of variables declaration//GEN-END:variables
}
